export const projects = [
  {
    img: "https://github.com/UdayCreative/react-todo-app/raw/main/TodoList.png",
    title: "Todo-App",
    des: "In the project, we will be creating a Complete Todo Application with all features. We will do all the CRUD operations. We will to use React.js and to manage our states, we will use Redux. Also we will learn to make simple animations using Framer Motion.",
    demo: "", 
    live: "https://my-todoslist-app.netlify.app/",
    gitHub: "https://github.com/UdayCreative/react-todo-app",
    technologies: ["HTML", "CSS", "SCSS", "framer-motion", "React.Js", "Redux", "Local Storage", "JavaScript"],
  },
  {
    img: "https://www.myticketstoindia.com/wp-content/uploads/2022/01/Travelocity.webp",
    title: "Travelocity-Clone",
    des: "Travelocity Clone website. Which is an online travel agency owned by Expedia Group. We added functionality like Signup, Login, Search Hotels & Cars, add to cart, and Payment Gateway. We used React, Redux, JavaScript, CSS, and Material UI to build this website.",
    demo: "", 
    live: "https://thriving-hamster-345ef4.netlify.app/",
    gitHub: "https://github.com/641krishna/-descriptive-payment-4603",
    technologies: ["HTML", "CSS", "SCSS", "framer-motion", "React.Js", "Redux", "Redux-Thunk", "Material-UI", "Local Storage", "JavaScript"],
  },
  {
    img: "https://wereview.in/wp-content/uploads/2015/09/bigbasket-review.png",
    title: "BigBasket-Clone",
    des: "BigBasket is an e-commerce website which primarily delivers grocery goods found in convenience stores, home essentials and food supplies to its customers. The best online grocery store in India. bigbasket is an online supermarket for all your daily needs.",
    demo: "",
    live: "https://venerable-basbousa-4536f8.netlify.app/",
    gitHub: "https://github.com/Vaibhav2416/BigBasket-Clone",
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
    ],
  },
  {
    img: "https://cdn.almowafir.com/1/Banggood-846x580.jpg",
    title: "Banggood-Clone",
    des: "This is the clone of Banggood website. Global Leading Online Shop. Buy 3d printer, rc toys, cell phones, home appliances, tv box, home & garden, apparel with great prices on banggood.com.",
    demo: "", 
    live: "https://banggood-clone-masai.netlify.app/",
    gitHub: "https://github.com/Kunal-Ladhani/Banggood-Clone",
    technologies: ["HTML", "CSS", "JavaScript"],
  },
];
